spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.3"

cards:
  message: "Welcome to EazyBank prod cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

