services:
  accounts:
    image: "lennydennis/account:s4"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mybank
  loans:
    image: "lennydennis/loans:s4"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mybank
  cards:
    image: "lennydennis/cards:s4"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mybank
networks:
  mybank:
    driver: "bridge"



