build:
  version: "1.5"

cards:
  message: "Welcome to EazyBank QA cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

