spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/LennyDennis/microservices-app.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #        native:
#          search-locations: "file:///home//lenny//Documents//Personal//Microservices//microservices-app//config"
        #          search-locations: "classpath:/config"


server:
  port: 8071